name: Build

on: 
  push:
    branches:
      - "release"

env:
  release_name: 0.1.${{github.run_number}}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '>=3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile main.py --name TextAutoTranslate --hidden-import=urllib3.contrib.resolver.system --hidden-import=urllib3.contrib.hface.protocols.http2 --hidden-import=urllib3.contrib.hface.protocols.http3  --noconsole


      - name: Create package directory
        run: mkdir -p dist/TextAutoTranslate
        

      - name: Move the built binary
        run: mv dist/TextAutoTranslate.exe dist/TextAutoTranslate/


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: TextAutoTranslate
          path: dist/

      - name: Download Artifact
        id: download
        uses: actions/download-artifact@v4.1.8

      - name: 'Create Release'
        shell: bash
        run: gh release create --generate-notes ${{ env.release_name }} dist/TextAutoTranslate/TextAutoTranslate.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
